-- 특별관리물질 보관 - 실제 확인수량 저장 테이블
-- 자동이월/입고반영 값은 매일 저장하지 않고 화면/출력 시 계산합니다.

create table if not exists public.qa_special_storage_daily (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  product_id bigint not null references public.product_master(id) on delete restrict,
  record_date date not null,
  quantity integer not null check (quantity >= 0),
  created_by text,
  created_name text,
  created_at timestamptz not null default now(),
  updated_by text,
  updated_name text,
  updated_at timestamptz not null default now(),
  constraint qa_special_storage_daily_unique unique (company_id, product_id, record_date)
);

create index if not exists idx_qa_special_storage_daily_company_date
  on public.qa_special_storage_daily(company_id, record_date);
create index if not exists idx_qa_special_storage_daily_product_date
  on public.qa_special_storage_daily(product_id, record_date);

create table if not exists public.qa_special_storage_history (
  id bigint generated by default as identity primary key,
  storage_record_id bigint,
  company_id uuid not null,
  product_id bigint not null,
  record_date date not null,
  old_quantity integer,
  new_quantity integer not null,
  changed_by text,
  changed_name text,
  changed_at timestamptz not null default now()
);

create index if not exists idx_qa_special_storage_history_product_date
  on public.qa_special_storage_history(company_id, product_id, record_date, changed_at);

-- 과거 날짜 조작 방지: 한국시간 기준 오늘 날짜만 INSERT/UPDATE 허용, DELETE 금지
create or replace function public.qa_special_storage_today_only()
returns trigger
language plpgsql
as $$
declare
  v_today date := (now() at time zone 'Asia/Seoul')::date;
begin
  if tg_op = 'DELETE' then
    raise exception '특별관리물질 보관수량 기록은 삭제할 수 없습니다.';
  end if;

  if new.record_date <> v_today then
    raise exception '특별관리물질 보관수량은 오늘 날짜만 입력/수정할 수 있습니다.';
  end if;

  if tg_op = 'UPDATE' and old.record_date <> new.record_date then
    raise exception '보관수량 확인일은 변경할 수 없습니다.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_qa_special_storage_today_only on public.qa_special_storage_daily;
create trigger trg_qa_special_storage_today_only
before insert or update or delete on public.qa_special_storage_daily
for each row execute function public.qa_special_storage_today_only();

-- 당일 수정이 발생해도 변경 이력은 별도 보존
create or replace function public.qa_special_storage_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.qa_special_storage_history(
    storage_record_id, company_id, product_id, record_date,
    old_quantity, new_quantity, changed_by, changed_name, changed_at
  ) values (
    new.id, new.company_id, new.product_id, new.record_date,
    case when tg_op = 'UPDATE' then old.quantity else null end,
    new.quantity,
    coalesce(new.updated_by, new.created_by),
    coalesce(new.updated_name, new.created_name),
    now()
  );
  return new;
end;
$$;

drop trigger if exists trg_qa_special_storage_audit on public.qa_special_storage_daily;
create trigger trg_qa_special_storage_audit
after insert or update on public.qa_special_storage_daily
for each row execute function public.qa_special_storage_audit();
