(function(){
  'use strict';
  const P=window.PatentCommon;
  let ctx=null, patents=[], deadlines=[], employees=[], currentPatent=null, detailData=null, editingId=null;
  const q=new URLSearchParams(location.search);

  const arr=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
  const labels={PATENT:'특허',UTILITY:'실용신안',DESIGN:'디자인',TRADEMARK:'상표'};

  async function init(){
    ctx=await P.resolveContext();
    if(!ctx.access.read){ document.querySelector('.pat-app').innerHTML='<div class="pat-error">특허관리 접근 권한이 없습니다.</div>'; return; }
    document.getElementById('newPatentBtn').disabled=!ctx.access.write;
    await Promise.all([loadEmployees(),loadList()]);
    bind();
    const openId=q.get('patent_id'); if(openId) await openDetail(openId);
  }

  function bind(){
    ['searchInput','countryFilter','typeFilter','statusFilter'].forEach(id=>document.getElementById(id).addEventListener(id==='searchInput'?'input':'change',renderList));
    document.getElementById('refreshBtn').addEventListener('click',()=>loadList().catch(err=>P.toast(err.message,'error')));
    document.getElementById('newPatentBtn').addEventListener('click',()=>openPatentModal());
    document.getElementById('savePatentBtn').addEventListener('click',savePatent);
    document.getElementById('kiprisLookupBtn').addEventListener('click',lookupKipris);
    document.getElementById('backBtn').addEventListener('click',showList);
    document.getElementById('editPatentBtn').addEventListener('click',()=>openPatentModal(currentPatent));
    document.getElementById('deletePatentBtn').addEventListener('click',deletePatent);
    document.getElementById('kiprisRefreshBtn').addEventListener('click',refreshKipris);
    document.querySelectorAll('[data-detail-tab]').forEach(btn=>btn.addEventListener('click',()=>switchDetailTab(btn.dataset.detailTab)));
    document.getElementById('uploadFileBtn').addEventListener('click',uploadFile);
    window.addEventListener('message',e=>{ if(e.data?.type==='portal-auth') setTimeout(()=>loadList().catch(()=>{}),100); });
  }

  async function loadEmployees(){
    try{
      const {data,error}=await P.state.client.from('employees').select('employee_no,name,email').eq('company_id',ctx.session.companyId).order('name'); if(error)throw error; employees=data||[];
    }catch(e){ console.warn(e); employees=[]; }
    const sel=document.getElementById('f_manager_employee_no'); sel.innerHTML='<option value="">선택</option>'+employees.map(e=>`<option value="${P.escapeHtml(e.employee_no)}">${P.escapeHtml(e.name||e.employee_no)} (${P.escapeHtml(e.employee_no)})</option>`).join('');
  }

  async function loadList(){
    const [pat,dead]=await Promise.all([
      P.companyQuery('pat_master','*').eq('is_active',true).order('created_at',{ascending:false}),
      P.companyQuery('pat_deadlines','patent_id,title,due_date,status').eq('status','OPEN').order('due_date',{ascending:true})
    ]); if(pat.error)throw pat.error;if(dead.error)throw dead.error; patents=pat.data||[];deadlines=dead.data||[];
    const countries=[...new Set(patents.map(x=>x.country_code).filter(Boolean))].sort(); const current=document.getElementById('countryFilter').value;
    document.getElementById('countryFilter').innerHTML='<option value="">전체 국가</option>'+countries.map(x=>`<option value="${P.escapeHtml(x)}">${P.escapeHtml(x)}</option>`).join(''); document.getElementById('countryFilter').value=current;
    renderList();
  }

  function nextDeadline(id){ return deadlines.find(x=>x.patent_id===id && P.daysUntil(x.due_date)!==null) || null; }
  function managerName(no){ if(!no)return '-'; return employees.find(x=>x.employee_no===no)?.name || no; }

  function renderList(){
    const search=P.clean(document.getElementById('searchInput').value).toLowerCase(), country=document.getElementById('countryFilter').value, type=document.getElementById('typeFilter').value, status=document.getElementById('statusFilter').value;
    const rows=patents.filter(p=>{
      const hay=[p.invention_title,p.application_no,p.registration_no,p.internal_no].join(' ').toLowerCase();
      return (!search||hay.includes(search))&&(!country||p.country_code===country)&&(!type||p.ip_type===type)&&(!status||P.classifyPatentStatus(p.legal_status)===status);
    });
    document.getElementById('resultCount').textContent=rows.length+'건';
    document.getElementById('patentBody').innerHTML=rows.length?rows.map((p,i)=>{ const d=nextDeadline(p.id); return `<tr class="clickable" data-id="${p.id}"><td>${i+1}</td><td>${P.escapeHtml(p.internal_no||'-')}</td><td><b>${P.escapeHtml(p.invention_title)}</b><div class="row-sub">${P.escapeHtml(p.application_no||p.registration_no||'')}</div></td><td>${P.escapeHtml(p.country_code||'-')}</td><td>${P.escapeHtml(labels[p.ip_type]||p.ip_type||'-')}</td><td>${P.badge(p.legal_status,P.patentStatusLabel(p.legal_status))}</td><td>${P.fmtDate(p.application_date)}</td><td>${P.fmtDate(p.registration_date)}</td><td>${P.fmtDate(p.expiration_date)}</td><td>${d?`<span class="pat-dday ${P.ddayClass(d.due_date)}">${P.dday(d.due_date)}</span><div class="row-sub">${P.escapeHtml(d.title)}</div>`:'-'}</td><td>${P.escapeHtml(managerName(p.manager_employee_no))}</td></tr>`; }).join(''):'<tr><td colspan="11" class="pat-empty">조건에 맞는 특허가 없습니다.</td></tr>';
    document.querySelectorAll('#patentBody tr[data-id]').forEach(tr=>tr.addEventListener('click',()=>openDetail(tr.dataset.id).catch(e=>P.toast(e.message,'error'))));
  }

  function clearForm(){ ['internal_no','application_no','application_date','publication_no','publication_date','registration_no','registration_date','legal_status','expiration_date','applicant_names','right_holder_names','agent_names','inventors','ipc_codes','cpc_codes','related_project','related_product_technology','abstract_text','memo'].forEach(k=>P.setVal('f_'+k,'')); P.setVal('f_ip_type','PATENT');P.setVal('f_country_code','KR');P.setVal('f_manager_employee_no','');P.setVal('lookupNo',''); }
  function openPatentModal(p=null){ if(!ctx.access.write)return; editingId=p?.id||null; clearForm(); document.getElementById('patentModalTitle').textContent=p?'특허 수정':'특허 등록'; if(p){ Object.entries({internal_no:p.internal_no,ip_type:p.ip_type,country_code:p.country_code,invention_title:p.invention_title,application_no:p.application_no,application_date:p.application_date,publication_no:p.publication_no,publication_date:p.publication_date,registration_no:p.registration_no,registration_date:p.registration_date,legal_status:p.legal_status,expiration_date:p.expiration_date,manager_employee_no:p.manager_employee_no,applicant_names:(p.applicant_names||[]).join(', '),right_holder_names:(p.right_holder_names||[]).join(', '),agent_names:(p.agent_names||[]).join(', '),ipc_codes:(p.ipc_codes||[]).join(', '),cpc_codes:(p.cpc_codes||[]).join(', '),related_project:p.related_project,related_product_technology:p.related_product_technology,abstract_text:p.abstract_text,memo:p.memo}).forEach(([k,v])=>P.setVal('f_'+k,v||'')); }
    if(p) P.companyQuery('pat_inventors','inventor_name').eq('patent_id',p.id).order('display_order').then(r=>{if(!r.error)P.setVal('f_inventors',(r.data||[]).map(x=>x.inventor_name).join(', '));}); P.modalOpen('patentModal'); }

  function formPayload(){ return P.companyPayload({internal_no:P.val('f_internal_no')||null,ip_type:P.val('f_ip_type')||'PATENT',country_code:(P.val('f_country_code')||'KR').toUpperCase(),invention_title:P.val('f_invention_title').trim(),application_no:P.val('f_application_no')||null,application_date:P.val('f_application_date')||null,publication_no:P.val('f_publication_no')||null,publication_date:P.val('f_publication_date')||null,registration_no:P.val('f_registration_no')||null,registration_date:P.val('f_registration_date')||null,legal_status:P.val('f_legal_status')||null,expiration_date:P.val('f_expiration_date')||null,manager_employee_no:P.val('f_manager_employee_no')||null,applicant_names:arr(P.val('f_applicant_names')),right_holder_names:arr(P.val('f_right_holder_names')),agent_names:arr(P.val('f_agent_names')),ipc_codes:arr(P.val('f_ipc_codes')),cpc_codes:arr(P.val('f_cpc_codes')),abstract_text:P.val('f_abstract_text')||null,related_project:P.val('f_related_project')||null,related_product_technology:P.val('f_related_product_technology')||null,memo:P.val('f_memo')||null,updated_by_employee_no:ctx.session.employeeNo||null}); }

  async function savePatent(){
    if(!ctx.access.write)return; const payload=formPayload(); if(!payload.invention_title){P.toast('발명의 명칭을 입력해 주세요.','warn');return;} const btn=this;btn.disabled=true;
    try{
      let row; if(editingId){ const {data,error}=await P.state.client.from('pat_master').update(payload).eq('id',editingId).eq('company_id',ctx.session.companyId).select().single(); if(error)throw error;row=data; }
      else{ payload.created_by_employee_no=ctx.session.employeeNo||null; const {data,error}=await P.state.client.from('pat_master').insert(payload).select().single(); if(error)throw error;row=data; }
      const names=arr(P.val('f_inventors')); await P.state.client.from('pat_inventors').delete().eq('patent_id',row.id).eq('company_id',ctx.session.companyId); if(names.length){ const {error}=await P.state.client.from('pat_inventors').insert(names.map((n,i)=>P.companyPayload({patent_id:row.id,inventor_name:n,display_order:i+1,source:'MANUAL'}))); if(error)throw error; }
      P.modalClose('patentModal');P.toast(editingId?'수정했습니다.':'등록했습니다.');editingId=null;await loadList(); if(currentPatent?.id===row.id)await openDetail(row.id);
    }catch(e){P.toast(e.message,'error');}finally{btn.disabled=false;}
  }

  function applyKiprisData(data){ const p=data?.patent||data?.data||data||{}; const map={invention_title:p.invention_title||p.title,application_no:p.application_no,application_date:p.application_date,publication_no:p.publication_no,publication_date:p.publication_date,registration_no:p.registration_no,registration_date:p.registration_date,legal_status:p.legal_status||p.status,expiration_date:p.expiration_date,country_code:p.country_code||'KR',abstract_text:p.abstract_text||p.abstract}; Object.entries(map).forEach(([k,v])=>{if(v)P.setVal('f_'+k,String(v).slice(0,k.includes('date')?10:9999));}); if(p.applicant_names)P.setVal('f_applicant_names',(Array.isArray(p.applicant_names)?p.applicant_names:[p.applicant_names]).join(', ')); if(p.right_holder_names)P.setVal('f_right_holder_names',(Array.isArray(p.right_holder_names)?p.right_holder_names:[p.right_holder_names]).join(', ')); if(p.agent_names)P.setVal('f_agent_names',(Array.isArray(p.agent_names)?p.agent_names:[p.agent_names]).join(', ')); if(p.inventors)P.setVal('f_inventors',(Array.isArray(p.inventors)?p.inventors:[p.inventors]).map(x=>typeof x==='string'?x:x.name||x.inventor_name).filter(Boolean).join(', ')); if(p.ipc_codes)P.setVal('f_ipc_codes',(Array.isArray(p.ipc_codes)?p.ipc_codes:[p.ipc_codes]).join(', ')); if(p.cpc_codes)P.setVal('f_cpc_codes',(Array.isArray(p.cpc_codes)?p.cpc_codes:[p.cpc_codes]).join(', ')); }
  async function lookupKipris(){ const no=P.val('lookupNo').trim(); if(!no){P.toast('출원번호 또는 등록번호를 입력해 주세요.','warn');return;} const btn=this;btn.disabled=true;try{const data=await P.invokeKipris({action:'lookup',number:no,company_id:ctx.session.companyId});applyKiprisData(data);P.toast('KIPRIS 정보를 불러왔습니다.');}catch(e){P.toast(e.message+' Edge Function 설정 전에는 직접 입력해 주세요.','error',4200);}finally{btn.disabled=false;} }

  async function openDetail(id){
    const p=patents.find(x=>x.id===id) || (await P.companyQuery('pat_master','*').eq('id',id).maybeSingle()).data; if(!p)throw new Error('특허 정보를 찾을 수 없습니다.'); currentPatent=p;
    const [inv,ev,pay,files,dead]=await Promise.all([
      P.companyQuery('pat_inventors','*').eq('patent_id',id).order('display_order'), P.companyQuery('pat_events','*').eq('patent_id',id).order('event_date',{ascending:false}), P.companyQuery('pat_payments','*').eq('patent_id',id).order('official_due_date',{ascending:false}), P.companyQuery('pat_files','*').eq('patent_id',id).order('created_at',{ascending:false}), P.companyQuery('pat_deadlines','*').eq('patent_id',id).order('due_date',{ascending:true})
    ]); [inv,ev,pay,files,dead].forEach(r=>{if(r.error)throw r.error;}); detailData={inventors:inv.data||[],events:ev.data||[],payments:pay.data||[],files:files.data||[],deadlines:dead.data||[]};
    document.getElementById('listView').classList.add('hidden');document.getElementById('detailView').classList.remove('hidden');
    document.getElementById('editPatentBtn').disabled=!ctx.access.write;document.getElementById('deletePatentBtn').disabled=!ctx.access.admin;document.getElementById('kiprisRefreshBtn').disabled=!ctx.access.write;
    renderHero(); switchDetailTab('basic'); history.replaceState(null,'','?patent_id='+encodeURIComponent(id));
  }

  function renderHero(){ const p=currentPatent; const next=detailData.deadlines.find(x=>x.status==='OPEN'); const remaining=P.daysUntil(p.expiration_date); let progress=0;if(p.application_date&&p.expiration_date){const s=new Date(p.application_date),e=new Date(p.expiration_date),n=new Date(); progress=Math.max(0,Math.min(100,(n-s)/(e-s)*100));}
    document.getElementById('detailHero').innerHTML=`<div class="pat-detail-top"><div><div class="pat-pill-row">${P.badge(p.legal_status,P.patentStatusLabel(p.legal_status))}<span class="pat-badge gold">${P.escapeHtml(p.country_code||'KR')}</span><span class="pat-badge gray">${P.escapeHtml(labels[p.ip_type]||p.ip_type||'특허')}</span></div><div class="pat-detail-title">${P.escapeHtml(p.invention_title)}</div><div class="pat-detail-meta"><span>사내번호 ${P.escapeHtml(p.internal_no||'-')}</span><span>출원일 ${P.fmtDate(p.application_date)}</span><span>등록일 ${P.fmtDate(p.registration_date)}</span><span>만료예정 ${P.fmtDate(p.expiration_date)}${remaining!==null?' ('+P.dday(p.expiration_date)+')':''}</span>${next?`<span class="pat-dday ${P.ddayClass(next.due_date)}">다음기한 ${P.fmtDate(next.due_date)} ${P.dday(next.due_date)}</span>`:''}</div></div></div>${p.expiration_date?`<div style="margin-top:12px"><div class="pat-progress"><span style="width:${progress}%"></span></div></div>`:''}`;
  }

  function showList(){ currentPatent=null;detailData=null;document.getElementById('detailView').classList.add('hidden');document.getElementById('listView').classList.remove('hidden');history.replaceState(null,'','./index.html'); }
  function switchDetailTab(tab){ document.querySelectorAll('[data-detail-tab]').forEach(b=>b.classList.toggle('active',b.dataset.detailTab===tab)); const el=document.getElementById('detailContent'); if(tab==='basic')renderBasic(el); if(tab==='events')renderEvents(el); if(tab==='inventors')renderInventors(el); if(tab==='payments')renderPayments(el); if(tab==='files')renderFiles(el); if(tab==='memo')renderMemo(el); }

  function renderBasic(el){ const p=currentPatent; el.innerHTML=`<div class="detail-basic-grid"><div><dl class="pat-info-grid"><dt>사내 관리번호</dt><dd>${P.escapeHtml(p.internal_no||'-')}</dd><dt>출원번호</dt><dd>${P.escapeHtml(p.application_no||'-')}</dd><dt>출원일</dt><dd>${P.fmtDate(p.application_date)}</dd><dt>공개번호</dt><dd>${P.escapeHtml(p.publication_no||'-')}</dd><dt>공개일</dt><dd>${P.fmtDate(p.publication_date)}</dd><dt>등록번호</dt><dd>${P.escapeHtml(p.registration_no||'-')}</dd><dt>등록일</dt><dd>${P.fmtDate(p.registration_date)}</dd><dt>존속기간 만료</dt><dd>${P.fmtDate(p.expiration_date)}</dd><dt>출원인</dt><dd>${P.escapeHtml((p.applicant_names||[]).join(', ')||'-')}</dd><dt>권리자</dt><dd>${P.escapeHtml((p.right_holder_names||[]).join(', ')||'-')}</dd><dt>대리인</dt><dd>${P.escapeHtml((p.agent_names||[]).join(', ')||'-')}</dd><dt>IPC</dt><dd>${P.escapeHtml((p.ipc_codes||[]).join(', ')||'-')}</dd><dt>CPC</dt><dd>${P.escapeHtml((p.cpc_codes||[]).join(', ')||'-')}</dd><dt>담당자</dt><dd>${P.escapeHtml(managerName(p.manager_employee_no))}</dd><dt>관련 연구과제</dt><dd>${P.escapeHtml(p.related_project||'-')}</dd><dt>관련 제품/기술</dt><dd>${P.escapeHtml(p.related_product_technology||'-')}</dd></dl></div><div class="detail-side"><div class="rights-box"><div class="pat-card-title">요약 정보</div><div class="summary-list"><div class="summary-row"><span>현재 상태</span><strong>${P.patentStatusLabel(p.legal_status)}</strong></div><div class="summary-row"><span>발명자</span><strong>${detailData.inventors.length}명</strong></div><div class="summary-row"><span>납부내역</span><strong>${detailData.payments.length}건</strong></div><div class="summary-row"><span>첨부문서</span><strong>${detailData.files.length}건</strong></div></div></div><div class="rights-box"><div class="pat-card-title">초록</div><div class="pat-card-desc abstract-box">${P.escapeHtml(p.abstract_text||'등록된 초록이 없습니다.')}</div></div><div class="rights-box"><div class="pat-card-title">KIPRIS 동기화</div><div class="pat-card-desc">최근 갱신: ${p.kipris_last_synced_at?P.fmtDate(p.kipris_last_synced_at):'미연동'}</div></div></div></div>`; }

  function renderEvents(el){ el.innerHTML=(ctx.access.write?`<div class="events-add"><div class="event-add-row"><input id="eventDate" type="date" class="pat-input"><input id="eventType" class="pat-input" placeholder="유형"><input id="eventTitle" class="pat-input" placeholder="진행이력 제목"><button id="addEventBtn" class="pat-btn primary">이력 추가</button></div></div>`:'')+`<div class="pat-timeline">${detailData.events.length?detailData.events.map(e=>`<div class="pat-timeline-item"><div class="pat-timeline-date">${P.fmtDate(e.event_date)}</div><div class="pat-timeline-title">${P.escapeHtml(e.title)}</div><div class="pat-timeline-desc">${P.escapeHtml(e.description||e.event_type||'')}</div></div>`).join(''):'<div class="pat-empty">진행이력이 없습니다.</div>'}</div>`; document.getElementById('addEventBtn')?.addEventListener('click',addEvent); }
  async function addEvent(){ const date=P.val('eventDate'),type=P.val('eventType')||'MANUAL',title=P.val('eventTitle');if(!title){P.toast('제목을 입력해 주세요.','warn');return;}const {error}=await P.state.client.from('pat_events').insert(P.companyPayload({patent_id:currentPatent.id,event_date:date||null,event_type:type,title,source:'MANUAL',created_by_employee_no:ctx.session.employeeNo||null}));if(error){P.toast(error.message,'error');return;}P.toast('진행이력을 추가했습니다.');await openDetail(currentPatent.id);switchDetailTab('events'); }
  function renderInventors(el){ el.innerHTML=`<div class="inventor-list">${detailData.inventors.length?detailData.inventors.map(i=>`<span class="inventor-chip">${P.escapeHtml(i.inventor_name)}</span>`).join(''):'<div class="pat-empty">등록된 발명자가 없습니다.</div>'}</div><div class="pat-note form-top-gap">발명자는 employees와 자동 매칭하지 않고 KIPRIS 또는 수기 입력 이름을 그대로 표시합니다.</div>`; }
  function renderPayments(el){ el.innerHTML=`<div class="pat-table-wrap"><table class="pat-table"><thead><tr><th>구분</th><th>대상연차</th><th>납부기한</th><th>방식</th><th>금액</th><th>상태</th><th>지급일</th></tr></thead><tbody>${detailData.payments.length?detailData.payments.map(x=>`<tr><td>${P.paymentTypeLabel(x.payment_type)}</td><td>${P.annualRangeLabel(x.annual_year_from,x.annual_year_to)}</td><td>${P.fmtDate(x.official_due_date||x.invoice_due_date)}</td><td>${P.paymentMethodLabel(x.payment_method)}</td><td class="num">${P.fmtMoney(x.paid_amount||x.billed_amount,x.currency)}</td><td>${P.badge(x.status,P.paymentStatusLabel(x.status))}</td><td>${P.fmtDate(x.paid_date)}</td></tr>`).join(''):'<tr><td colspan="7" class="pat-empty">납부내역이 없습니다.</td></tr>'}</tbody></table></div><div style="margin-top:10px"><button class="pat-btn secondary" id="goPaymentsBtn">납부관리로 이동</button></div>`; document.getElementById('goPaymentsBtn').addEventListener('click',()=>P.navigate('management',{section:'payments',patent_id:currentPatent.id})); }
  function fileCategoryLabel(v){return ({APPLICATION:'출원서',SPECIFICATION:'명세서',PUBLICATION:'공보',CERTIFICATE:'등록증',OFFICE_ACTION:'의견제출통지',RESPONSE:'의견서/보정서',INVOICE:'청구서',PAYMENT_PROOF:'납부/지급증빙',DRAWING:'도면',OTHER:'기타'})[v]||v;}
  function renderFiles(el){ el.innerHTML=`${ctx.access.write?'<div style="margin-bottom:10px"><button id="openFileModalBtn" class="pat-btn primary">＋ 파일 업로드</button></div>':''}<div class="pat-table-wrap"><table class="pat-table"><thead><tr><th>구분</th><th>파일명</th><th>설명</th><th>등록일</th><th>관리</th></tr></thead><tbody>${detailData.files.length?detailData.files.map(f=>`<tr><td>${fileCategoryLabel(f.file_category)}</td><td>${P.escapeHtml(f.original_file_name)}</td><td>${P.escapeHtml(f.description||'-')}</td><td>${P.fmtDate(f.created_at)}</td><td><div class="file-actions"><button class="pat-btn" data-file-open="${f.id}">열기</button>${ctx.access.write?`<button class="pat-btn danger" data-file-delete="${f.id}">삭제</button>`:''}</div></td></tr>`).join(''):'<tr><td colspan="5" class="pat-empty">첨부문서가 없습니다.</td></tr>'}</tbody></table></div>`; document.getElementById('openFileModalBtn')?.addEventListener('click',()=>P.modalOpen('fileModal')); el.querySelectorAll('[data-file-open]').forEach(b=>b.addEventListener('click',()=>{const f=detailData.files.find(x=>x.id===b.dataset.fileOpen);P.downloadPatentFile(f).catch(e=>P.toast(e.message,'error'));})); el.querySelectorAll('[data-file-delete]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('파일을 삭제할까요?'))return;const f=detailData.files.find(x=>x.id===b.dataset.fileDelete);try{await P.deletePatentFile(f);P.toast('삭제했습니다.');await openDetail(currentPatent.id);switchDetailTab('files');}catch(e){P.toast(e.message,'error');}})); }
  function renderMemo(el){ el.innerHTML=`<div class="memo-editor"><textarea id="memoText" class="pat-textarea" ${ctx.access.write?'':'readonly'}>${P.escapeHtml(currentPatent.memo||'')}</textarea>${ctx.access.write?'<div><button id="saveMemoBtn" class="pat-btn primary">메모 저장</button></div>':''}</div>`; document.getElementById('saveMemoBtn')?.addEventListener('click',async()=>{const {data,error}=await P.state.client.from('pat_master').update({memo:P.val('memoText'),updated_by_employee_no:ctx.session.employeeNo||null}).eq('id',currentPatent.id).eq('company_id',ctx.session.companyId).select().single();if(error){P.toast(error.message,'error');return;}currentPatent=data;P.toast('메모를 저장했습니다.');}); }

  async function uploadFile(){ const file=document.getElementById('fileInput').files?.[0];if(!file){P.toast('파일을 선택해 주세요.','warn');return;}const btn=this;btn.disabled=true;try{await P.uploadPatentFile({patentId:currentPatent.id,file,category:P.val('fileCategory'),description:P.val('fileDesc')});P.modalClose('fileModal');document.getElementById('fileInput').value='';P.setVal('fileDesc','');P.toast('파일을 업로드했습니다.');await openDetail(currentPatent.id);switchDetailTab('files');}catch(e){P.toast(e.message,'error',4500);}finally{btn.disabled=false;} }

  async function deletePatent(){ if(!ctx.access.admin||!currentPatent)return;if(!confirm('이 특허와 연결된 이력/납부/파일 정보를 삭제할까요?'))return;const {error}=await P.state.client.from('pat_master').delete().eq('id',currentPatent.id).eq('company_id',ctx.session.companyId);if(error){P.toast(error.message,'error');return;}P.toast('특허를 삭제했습니다.');showList();await loadList(); }

  async function refreshKipris(){ if(!ctx.access.write||!currentPatent)return;const number=currentPatent.application_no||currentPatent.registration_no;if(!number){P.toast('출원번호 또는 등록번호가 없습니다.','warn');return;}const btn=this;btn.disabled=true;try{const data=await P.invokeKipris({action:'lookup',number,company_id:ctx.session.companyId});const p=data?.patent||data?.data||data||{};const upd={};['invention_title','application_no','application_date','publication_no','publication_date','registration_no','registration_date','legal_status','expiration_date','abstract_text','public_notice_url','registration_notice_url','representative_image_url'].forEach(k=>{if(p[k]!=null)upd[k]=p[k];});if(p.applicant_names)upd.applicant_names=Array.isArray(p.applicant_names)?p.applicant_names:[p.applicant_names];if(p.right_holder_names)upd.right_holder_names=Array.isArray(p.right_holder_names)?p.right_holder_names:[p.right_holder_names];if(p.agent_names)upd.agent_names=Array.isArray(p.agent_names)?p.agent_names:[p.agent_names];if(p.ipc_codes)upd.ipc_codes=Array.isArray(p.ipc_codes)?p.ipc_codes:[p.ipc_codes];if(p.cpc_codes)upd.cpc_codes=Array.isArray(p.cpc_codes)?p.cpc_codes:[p.cpc_codes];upd.kipris_last_synced_at=new Date().toISOString();upd.kipris_raw=p;const {error}=await P.state.client.from('pat_master').update(upd).eq('id',currentPatent.id).eq('company_id',ctx.session.companyId);if(error)throw error;if(p.inventors){const names=(Array.isArray(p.inventors)?p.inventors:[p.inventors]).map(x=>typeof x==='string'?x:x.name||x.inventor_name).filter(Boolean);await P.state.client.from('pat_inventors').delete().eq('patent_id',currentPatent.id).eq('company_id',ctx.session.companyId);if(names.length)await P.state.client.from('pat_inventors').insert(names.map((n,i)=>P.companyPayload({patent_id:currentPatent.id,inventor_name:n,display_order:i+1,source:'KIPRIS'})));}P.toast('KIPRIS 정보를 갱신했습니다.');await loadList();await openDetail(currentPatent.id);}catch(e){P.toast(e.message+' Edge Function 설정을 확인해 주세요.','error',4500);}finally{btn.disabled=false;} }

  init().catch(e=>{console.error(e);document.querySelector('.pat-app').innerHTML='<div class="pat-error">'+P.escapeHtml(e.message)+'</div>';});
})();
